name: dashboard
description: Dynamic dashboard widget that allows your users to create their own layouts. Rezise, move, indirect resize/move, auto
  re-layout are supported.
version: 0.0.2+4
homepage: https://github.com/Mehmetyaz/dashboard
repository: https://github.com/Mehmetyaz/dashboard

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
